### ISSUE TITLE
Refatorar o histórico de operações

### ISSUE THREAD

**Issue by jpechaves** [sosolidkk/aula_git#32]
Alterar a operação do método addOperation(), pois está faltando adicionar o caso referente ao dado do remetente, pois só possui o do destinatário.

**Comment by netochaves** [comment]
não ficou claro, tem como explicar melhor?

**Comment by jpechaves** [comment]
Seguinte, estava discutindo com o Max e as operações que a gente faz e pegar o tipo da operação, o valor e o destinatário dessa operação, que no caso funciona perfeitamente para depósito e saque. Porém na transferência, é necessário saber QUEM enviou pra ONDE, ou seja, remetente -> destinatário. Essa issue é referente somente a esse caso específico que está faltando.
